apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpressweb
        image: wbchokouago/cr460-ts2018:latest
        ports:
        - containerPort: 80
        env:
          - name: DB_PASSWORD
            value: "sqlpa55"
          - name: DB_HOST
            value: "127.0.0.1:3306"
          - name: DB_USER
            value: "root"
          - name: DB_NAME
            value: "sql460"
      - name: wordpressdb
        image: mysql
        env:
          - name: MYSQL_PASSWORD
            value: "sqlpa55"
          - name: MYSQL_ROOT_PASSWORD
            value: "sqlpa55"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_DATABASE
            value: "sql460"